In [2]:
import numpy as np

### np.sum()
    syntax: 
        np.sum() --> returns value
### mean()
    * np.mean(arr) --> returns value
    * np.var(arr) --> returns value
    * np.std(arr) --> returns value

In [3]:
arr1=np.array([1,2,3,4])
arr2=np.array([[1,2,3,4],[5,6,7,8]])
print(arr1)
print(arr2)
print(arr1.ndim)
print(arr2.ndim)

[1 2 3 4]
[[1 2 3 4]
 [5 6 7 8]]
1
2


### sum -> sumof the all elements of an array

In [4]:
np.sum(arr1)

10

## axis = 0 -> columns wise

In [9]:
np.sum(arr1,axis=0)

10

## axis = 1 -> row wise

In [10]:
np.sum(arr2,axis=1)

array([10, 26])

## mean(average) -> sum of all elements / total no_of_elements

In [11]:
np.mean(arr1)

2.5

In [18]:
np.mean(arr2)

4.5

## var(variance) -> average of square difference from mean
    Mean = 2.5
    Differences = [-1.5, -0.5, 0.5, 1.5]
    Squared = [2.25, 0.25, 0.25, 2.25]
    Variance = (2.25 + 0.25 + 0.25 + 2.25) / 4 = 5 / 4 = 1.25

In [12]:
np.var(arr1)

1.25

In [15]:
np.var(arr2)

5.25

## std(standard deviation) -> square root of variance

In [13]:
np.std(arr1)

1.118033988749895

In [16]:
np.std(arr2)

2.29128784747792

In [19]:
arr3=np.array(['s','u','m','a','n'])

In [21]:
np.mean(arr3)

UFuncTypeError: ufunc 'add' did not contain a loop with signature matching types (dtype('<U1'), dtype('<U1')) -> None

In [22]:
np.var(arr3)

UFuncTypeError: ufunc 'add' did not contain a loop with signature matching types (dtype('<U1'), dtype('<U1')) -> None

In [23]:
np.std(arr3)

UFuncTypeError: ufunc 'add' did not contain a loop with signature matching types (dtype('<U1'), dtype('<U1')) -> None

### np.sort()


In [34]:
arr1=np.array([1,2,3,5,4])
arr2=np.array([[1000,100],[10,4]])

In [38]:
np.sort(arr1)

array([1, 2, 3, 4, 5])

In [41]:
np.sort(arr2) # row wise performing the operation

array([[ 100, 1000],
       [   4,   10]])

In [44]:
np.sort(arr2[0:,0:])

array([[ 100, 1000],
       [   4,   10]])

In [50]:
arr5=np.array([1,10,20,30,5])
np.sort(arr5[:-1])

array([ 1, 10, 20, 30])

In [58]:
arr6=np.array([[10,2,5],[20,200,1],[6,3,2]])
np.sort(arr6[:,::-1])

array([[  2,   5,  10],
       [  1,  20, 200],
       [  2,   3,   6]])

In [59]:
np.sort(arr6[::1,::-1])

array([[  2,   5,  10],
       [  1,  20, 200],
       [  2,   3,   6]])

In [ ]:
import copy # it's a module

: 

In [ ]:
arr7=np.array([[1,5,10]])

In [ ]:
arr8=np.array([[10,20],[45,6]])
c_arr8=copy.copy(arr8)
c_arr8

array([[10, 20],
       [45,  6]])

In [ ]:

arr8
c_arr8

array([[10, 20],
       [45,  6]])

In [ ]:
arr9=np.array([1,2,3,4,5])
arr9_c=copy.copy(arr9)
print(arr9)
print(arr9_c)

In [66]:
arr10=np.array([[1,2],[4,5]])

In [ ]:

arr10_c=copy.copy(arr10)
arr10_c[0][0]=100
print(arr10)
print(arr10_c)

print(id(arr10[0][0]),id(arr10_c[0][0]))

[[1 2]
 [4 5]]
[[100   2]
 [  4   5]]


In [ ]:
arr=np.array([[1,2],[4,5]])
arr_c=arr.view()
arr[0][0]=100
print(arr)
print(arr_c)

In [1]:
####################################

In [2]:
import numpy as np

In [4]:
arr=np.array([[10,2],[4,2]])
arr1=np.array([1.,2,3,4,5])
print(np.max(arr))
print(np.max(arr1))
np.max(arr1)

10
5.0


5.0