In [1]:
res=list(range(1,11,1.5)) # only integer is possible in step value
res

TypeError: 'float' object cannot be interpreted as an integer

In [2]:
import numpy as np

In [3]:
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
np.arange(1,11,3.5)

array([1. , 4.5, 8. ])

In [5]:
np.arange(1,11,0.5)

array([ 1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5,  5. ,  5.5,  6. ,
        6.5,  7. ,  7.5,  8. ,  8.5,  9. ,  9.5, 10. , 10.5])

In [7]:
np.linspace(1,10,5)

    # 1 - 10 num =4
    
    # 1 4 7 10
    # 1-4=>3
    # 4-7=>3
    # 7-10=>3

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [8]:
np.linspace(1,10,5)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [9]:
np.linspace(0,10)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

In [10]:
np.linspace(10)

TypeError: linspace() missing 1 required positional argument: 'stop'

In [11]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# array.shape -> returns shape of that array

In [2]:
# arr.shape
arr=np.array([[10,20],[11,12]])
arr1=np.array([1,2,3,4,5])
print(arr.shape)
print(arr1.shape)

(2, 2)
(5,)


In [6]:
arr=np.array([[10,20],[11,12],[11,22]])
print(arr.shape)

(3, 2)


In [16]:
arr.ndim

2

# array.ndim -> return dimension of an array

In [20]:
arr2=np.array([[[10,20],[20,50]],[[20,50],[70,80]],[[11,2],[4,5]]])
arr2.ndim

3

## array.dtype -> returns datatype of the array like -> dtype('int64')

In [19]:
arr.dtype

dtype('int32')

## array.size -> returns total numbers of values present in an array(integer)
### Ex: row x columns -->> row ->2,col ->3 ==>> returns 6

In [ ]:
arr=np.array([[10,20,10],[1,2,3],[3,4,7],[5,7,22]])
arr.size

12

In [23]:
arr4=np.array([1,2,3,4,5])
arr4[2:4]

array([3, 4])

In [27]:
arr4[:]

array([1, 2, 3, 4, 5])

In [38]:
arr5=np.array([[10,25,26],[1,2,3],[70,80,90]])
arr5[1:3,1:3]
arr5[1:,1:]

array([[ 2,  3],
       [80, 90]])

In [ ]:
arr6=np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15],[16,17,18,19,20],[21,22,23,24,25]])
arr6[1:3,1:4]


array([[ 7,  8,  9],
       [12, 13, 14]])

In [8]:
arr6[2:,:3]

array([[11, 12, 13],
       [16, 17, 18],
       [21, 22, 23]])

In [13]:
arr6[3:,3:]

array([[19, 20],
       [24, 25]])

In [14]:
arr6[1:3,4]

array([10, 15])