In [3]:
import numpy as np

In [6]:
# array() --> it's numpy method use to create array in python
'''
    syntax:
        np.array(value) --> value can be list/tuple/nested list/nested tuple
'''

arr=np.array([1,2,3,4,5])
print(arr,type(arr))


[1 2 3 4 5] <class 'numpy.ndarray'>


In [7]:
arr=np.array([1,2,3,4,5.5])
print(arr,type(arr))

[1.  2.  3.  4.  5.5] <class 'numpy.ndarray'>


In [12]:
arr=np.array([1,2,3,4,5,'sum'])
print(arr,type(arr))
arr


['1' '2' '3' '4' '5' 'sum'] <class 'numpy.ndarray'>


array(['1', '2', '3', '4', '5', 'sum'], dtype='<U11')

In [10]:
arr=np.array([1,2,3,4,5.7,True])
print(arr,type(arr))


[1.  2.  3.  4.  5.7 1. ] <class 'numpy.ndarray'>


In [16]:
arr=np.array([1,1,5,10,45.6],dtype = int)
arr


array([ 1,  1,  5, 10, 45])

In [18]:
arr=np.array(['hi','hello','hiiiiiiiiiiiii'],dtype='<U5')
arr

array(['hi', 'hello', 'hiiii'], dtype='<U5')

In [21]:
arr=np.array([1,2,3,4])
arr+2
arr

array([1, 2, 3, 4])

In [22]:
arr*7

array([ 7, 14, 21, 28])