In [1]:
import numpy as np

In [2]:
arr=np.array([1,2,3,4,5])
print(arr,type(arr))

[1 2 3 4 5] <class 'numpy.ndarray'>


In [3]:
arr=np.array([1,2,3,4,5.5])
print(arr,type(arr))

[1.  2.  3.  4.  5.5] <class 'numpy.ndarray'>


In [ ]:
arr2=np.array([1,2,5.5,'hi'])
print(arr2,type(arr2))

['1' '2' '5.5' 'hi'] <class 'numpy.ndarray'>


In [5]:
arr3=np.array([1,2,3,34.4],dtype=int)
# print(arr3+2)
# print(arr3*7)
arr3

array([ 1,  2,  3, 34])

In [6]:
arr4=np.array(['hi','sum'])
arr4

array(['hi', 'sum'], dtype='<U3')

In [10]:
res=list(range(1,11))
res

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [8]:
res=list(range(1,11,1.5))

TypeError: 'float' object cannot be interpreted as an integer

In [20]:
np.arange(1,11,1)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [23]:
np.linspace(11)

TypeError: linspace() missing 1 required positional argument: 'stop'

In [29]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([[1,2,3], [4,5,6]])
a.ndim
b.ndim

2

In [30]:
arr=np.array(['hi','sum'])
arr.dtype

dtype('<U3')

In [34]:
arr5=np.array([[10,25,26],
               [1,2,3],
               [70,80,90]])
arr5[1:3,1:3]
# arr5[1:,1:]

array([[ 2,  3],
       [80, 90]])

In [35]:
arr6=np.array([[1,2,3,4,5],
               [6,7,8,9,10],
               [11,12,13,14,15],
               [16,17,18,19,20],
               [21,22,23,24,25]])
arr6[1:3,1:4]

array([[ 7,  8,  9],
       [12, 13, 14]])

In [36]:
arr6[2:,:3]

array([[11, 12, 13],
       [16, 17, 18],
       [21, 22, 23]])

In [37]:
arr6[3:,3:]

array([[19, 20],
       [24, 25]])

In [39]:
arr6[1:3,4:]

array([[10],
       [15]])

In [51]:
arr=np.array([[12,20,30],[11,12,1]])
arr.ravel()

array([12, 20, 30, 11, 12,  1])

In [42]:
r_arr=arr.ravel()
r_arr

array([12, 20, 30, 11, 12,  1])

In [52]:
m_arr=np.array([[10,20],[30,40]])
f_arr=m_arr.flatten()
r_arr=m_arr.ravel()
print(m_arr)
print(f_arr)
print(r_arr)
f_arr[0]=1000
print(m_arr)
print(f_arr)
r_arr[2]=200
print(m_arr)
print(r_arr)

[[10 20]
 [30 40]]
[10 20 30 40]
[10 20 30 40]
[[10 20]
 [30 40]]
[1000   20   30   40]
[[ 10  20]
 [200  40]]
[ 10  20 200  40]


In [71]:
arr=np.array([[12,20,30],[11,12,1]])
# arr.resize(2,2)
arr

array([[12, 20, 30],
       [11, 12,  1]])

In [82]:
np.sum(arr,axis=1)

array([62, 24])

In [76]:
np.sum(arr,axis=0)

array([23, 32, 31])

In [81]:
np.mean(arr)
np.mean(arr,axis=0)
np.mean(arr,axis=1)

array([20.66666667,  8.        ])